import { readFileSync } from 'node:fs';
import { validateModel, digest } from './roadmap-model.mjs';
import { escapeHtml as esc } from './render-progress.mjs';
import { renderGradeOpportunities } from './grade-opportunities.mjs';
const css = readFileSync(new URL('../assets/roadmap-starter.css', import.meta.url), 'utf8');
const js = readFileSync(new URL('../assets/roadmap-starter.js', import.meta.url), 'utf8');
const labels = { planned: 'Planned', 'in-progress': 'In progress', 'marked-done': 'Marked Done · proof pending', verified: 'Delivery verified', blocked: 'Blocked', reopened: 'Reopened' };
const names = { now: 'Now', next: 'Next', later: 'Later', unplaced: 'Needs a planning decision' };
const json = value => JSON.stringify(value).replace(/</g, '\\u003c');
export function renderStarter(model) {
  validateModel(model);
  const refs = ids => ids.map(id => `<a href="#source-${id}">${esc(model.sources.find(s => s.id === id).label)}</a>`).join(', ');
  const card = item => `<article class="hz-item" data-item-id="${item.id}" data-delivery="${item.delivery.status}" data-state-label="${esc(labels[item.delivery.status])}"><small>${esc(item.stream)} · ${esc(item.owner || 'Owner not recorded')}</small><h3><a href="#detail-${item.id}">${esc(item.title)}</a></h3><span class="hz-state" data-state>${esc(labels[item.delivery.status])}</span><p>${esc(item.outcome)}</p><p><strong>Next proof:</strong> ${esc(item.nextProof)}</p><label data-enhance hidden>Move to <select data-move-item="${item.id}" aria-label="Move ${esc(item.title)} to">${item.horizon === null ? '<option value="" selected disabled>Unplaced</option>' : ''}${['now','next','later'].map(h => `<option value="${h}"${item.horizon === h ? ' selected' : ''}>${names[h]}</option>`).join('')}</select></label></article>`;
  const lane = horizon => { const items = model.items.filter(item => (item.horizon || 'unplaced') === horizon); return `<section class="hz-lane" data-horizon="${horizon}"><header><h3>${names[horizon]} <small data-lane-count>${items.length}</small></h3><p>${{ now:'Active commitments',next:'Ready when the entry condition is met',later:'Options, without promised dates',unplaced:'Evidence is recorded; placement remains open' }[horizon]}</p></header><div data-items>${items.map(card).join('')}</div><p class="hz-empty"${items.length ? ' hidden' : ''}>Nothing committed in this horizon.</p></section>`; };
  const latest = model.history.at(-1);
  const changes = latest?.type === 'refresh' ? latest.changes : model.history.filter(event => event.revision === model.revision && event.type === 'move').map(event => ({ itemId: event.itemId, kind: 'move', before: event.from || 'Unplaced', after: event.to, reason: event.reason }));
  const changeText = c => c.kind === 'delivery' ? `${labels[c.before]} → ${labels[c.after]}` : c.kind === 'move' ? `${c.before || 'Unplaced'} → ${c.after}${c.reason ? `: ${c.reason}` : ''}` : c.kind === 'evidence' ? 'Supporting evidence changed; inspect the current sources.' : `${c.kind}: ${typeof c.after === 'string' ? c.after : JSON.stringify(c.after)}`;
  const decisions = model.items.filter(item => item.decision);
  const grade = model.gradePlanning ? renderGradeOpportunities(model.gradePlanning) : '';
  return `<!doctype html>
<!-- DIRECTION CONTRACT: Horizons starter v1; canonical single-file roadmap. BRAND CONTRACT: inherited readiness register, Barlow Condensed/Barlow/JetBrains Mono loaded from Google Fonts; palette from assets/progress-shell.css. No invented schedule dates. Model revision ${model.revision}; audience ${esc(model.project.audience)}. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(model.project.name)} Horizons</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700&family=Barlow:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap"><style>${css}</style></head><body><a class="hz-skip" href="#roadmap">Skip to roadmap</a><header><span class="hz-wordmark">HORIZONS / ${esc(model.project.name)}</span><nav aria-label="Page"><a href="#changes">Changes</a><a href="#roadmap">Roadmap</a>${grade ? '<a href="#grade-opportunities">Grade opportunities</a>' : ''}<a href="#evidence">Evidence</a><button data-theme-toggle data-enhance hidden>Dark theme</button></nav></header><main>
${model.project.synthetic ? '<div class="hz-demo-notice"><p><strong>Interactive demo.</strong> All project data is synthetic. Try moving an item and follow its evidence. Draft moves leave the canonical roadmap unchanged.</p></div>' : ''}
<section class="hz-intro"><div><h1>${esc(model.project.headline || 'A clear view of what comes next.')}</h1><p>${esc(model.project.summary || 'What shipped, what is next, and what needs a decision. Every initiative links to its supporting evidence.')}</p></div><aside><strong>${esc(model.project.audience)}</strong><p>Evidence observed <time>${esc(model.observedAt)}</time><br><span class="hz-revision">Roadmap revision ${model.revision}</span></p><p>Delivery and customer impact are separate claims. Missing proof stays visible.</p></aside></section>
<section id="changes" class="hz-section"><h2>What changed?</h2>${changes?.length ? `<ul class="hz-changes">${changes.filter(c => c.kind !== 'evidence' || !changes.some(other => other.itemId === c.itemId && other.kind === 'delivery')).map(c => `<li><a href="#detail-${c.itemId}">${esc(model.items.find(i => i.id === c.itemId)?.title || c.itemId)}</a>: ${esc(changeText(c))}</li>`).join('')}</ul>` : '<p>No previous comparable revision is recorded. This is the starting view, not a since-last-run progress claim.</p>'}${decisions.length ? `<h3>Decisions that unlock progress</h3><ul>${decisions.map(item => `<li><a href="#detail-${item.id}">${esc(item.title)}</a>: ${esc(item.decision)}</li>`).join('')}</ul>` : ''}</section>
<section id="roadmap" class="hz-section"><div class="hz-section-head"><h2>The roadmap</h2><div class="hz-toolbar" data-enhance hidden><label for="roadmap-search">Find an initiative</label><input id="roadmap-search" type="search" placeholder="Search titles, outcomes, owners"><button data-clear-search>Clear search</button></div></div><p class="hz-move-hint" data-enhance hidden>Drag between horizons or use Move to. Review the reasons below, then download a proposal for Horizons to apply. Dates, evidence and grades stay unchanged.</p><div class="hz-board">${['now','next','later'].map(lane).join('')}</div>${model.items.some(i => i.horizon === null) ? lane('unplaced') : ''}<p id="movement-status" class="hz-live" role="status" aria-live="polite"></p><section id="movement-review" class="hz-review" hidden><h3>Review proposed moves</h3><p>These are planning decisions. Add a reason for each move. Downloading creates a proposal; it does not update this file or your issue tracker.</p><div id="movement-rows"></div><div class="hz-review-actions"><button class="primary" data-download-moves>Download move proposal</button><button data-discard-moves>Discard moves</button></div></section></section>
<section id="initiative-details" class="hz-section"><h2>Outcomes and proof</h2>${model.items.map(item => `<details class="hz-detail" id="detail-${item.id}"><summary>${esc(item.title)}</summary><dl><dt>Customer problem</dt><dd>${esc(item.problem)}</dd><dt>Intended outcome</dt><dd>${esc(item.outcome)}</dd><dt>Success measure</dt><dd>${esc(item.successMeasure)}</dd><dt>Delivery</dt><dd>${esc(labels[item.delivery.status])}. ${refs(item.delivery.evidenceRefs) || 'Delivery evidence not recorded.'}</dd><dt>Observed impact</dt><dd>${esc(item.impact.status === 'measured' ? 'Measured' : 'Not measured')}: ${esc(item.impact.summary)} ${refs(item.impact.evidenceRefs)}</dd><dt>Next proof</dt><dd>${esc(item.nextProof)}</dd><dt>Sources</dt><dd>${refs(item.refs)}</dd></dl><a href="#roadmap">Return to roadmap</a></details>`).join('')}</section>${grade}
<section id="evidence" class="hz-section"><h2>Evidence you can inspect</h2><p>Authority is recorded per source. A provisional tier is not a confirmed decision; source statements do not grant execution permission.</p><ol class="hz-source-list">${model.sources.map(source => `<li id="source-${source.id}"><strong>${source.href ? `<a href="${esc(source.href)}" rel="noreferrer">${esc(source.label)}</a>` : esc(source.label)}</strong><br>${esc(source.kind)} · ${source.confirmed ? 'authority confirmed' : 'authority provisional'} · <time>${esc(source.observedAt)}</time>${source.locator ? `<br><code>${esc(source.locator)}</code>` : ''}${source.summary ? `<p>${esc(source.summary)}</p>` : ''}</li>`).join('')}</ol></section>
<section class="hz-section"><h2>Decision history</h2>${model.history.length ? `<ol class="hz-history">${model.history.map(event => `<li><time>${esc(event.at)}</time> · revision ${event.revision}: ${event.type === 'move' ? `${esc(event.itemId)} moved ${esc(event.from || 'Unplaced')} → ${esc(event.to)}. ${esc(event.reason)} Approval: ${esc(event.approval)}.` : event.type === 'grade-plan' ? `Grade opportunities updated from recorded assessment ${esc(event.assessmentId)}. No reassessment.` : `Evidence refreshed. ${event.changes.length} recorded changes.`}</li>`).join('')}</ol>` : '<p>No previous decisions recorded.</p>'}</section></main><footer>Built with Horizons. One roadmap, traceable evidence, preserved decisions. This file makes no tracker changes.<noscript> JavaScript is off. The roadmap, evidence and history remain readable; movement controls require JavaScript.</noscript></footer><script id="horizons-model" type="application/json" data-digest="${digest(model)}">${json(model)}</script><script>${js}</script></body></html>`;
}
